# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: "en-US"

early_access: true

reviews:
  profile: assertive
  request_changes_workflow: true
  collapse_walkthrough: false
