repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.13.0
      hooks:
      -   id: mypy
          additional_dependencies: ["types-Flask"]
          files: flask_utils
          args: [ "--strict" ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-case-conflict
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: forbid-submodules
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: name-tests-test
        args: [--pytest-test-first]
        exclude: tests/utils.py
  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v1.0.0
    hooks:
      - id: sphinx-lint
        args:
          - -i .venv
          - -i .tox
