comment:
  after_n_builds: 4
  layout: " diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: false        # [true :: must have a base report to post]
  require_head: false       # [true :: must have a head report to post]
  hide_project_coverage: false # [true :: only show coverage on the git diff]

codecov:
  disable_default_path_fixes: true # Automatic detection does not discover all files

fixes:
  - "::flask_utils/"

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto

individual_components:
  - component_id: module_decorators
    name: decorators
    paths:
      - flask_utils/decorators.py
  - component_id: module_errors
    name: errors
    paths:
      - flask_utils/errors/**
