name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Setup Python
        run: uv python install
      - name: Run Ruff
        run: uv run ruff check --output-format=github .
  type-checking:
    name: Type Checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Setup Python
        run: uv python install
      - name: Run mypy
        # Using strict mode.
        # Waiting for https://github.com/python/mypy/pull/17771
        run: uv run mypy --strict flask_utils
